FROM node:9.4.0-alpine AS build-env
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install

FROM gcr.io/distroless/nodejs
WORKDIR /usr/src/app
COPY --from=build-env . .
ENV NODE_ENV "development"
EXPOSE 8080
CMD [ "npm", "run", "dev" ]