apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: gcr.io/skilful-orb-210513/quakes-ui
  googleCloudBuild:
    projectId: skilful-orb-210513
deploy:
  kubectl:
    manifests:
      - quakes-ui.yaml
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: skilful-orb-210513
  - name: kaniko
    build:
      kaniko:
        gcsBucket: k8s-skaffold
        pullSecret: /a/secret/path/serviceaccount.json
        namespace: default
  - name: local
    build:
      local:
        skipPush: true