apiVersion: skaffold/v1alpha2
kind: Config
build:
  artifacts:
  - imageName: chzbrgr71/quakes-ui
    docker: {}
  local:
    skipPush: False
deploy:
  kubectl:
    manifests:
      - quakes-ui-dev.yaml